version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-toastify
    versions:
    - 7.0.3
  - dependency-name: react-redux
    versions:
    - 7.2.3
